[".vim/colors/gruvbox.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/morhetz/gruvbox/master/colors/gruvbox.vim"
    exact = true
    stripComponents = 1
{{- if and (not .ephemeral) (not .headless) }}
{{-   $fontDir := "" }}
{{-   if eq .chezmoi.os "darwin" }}
{{-     $fontDir = "Library/Fonts" }}
{{-   else if eq .chezmoi.os "linux" }}
{{-     $fontDir = ".local/share/fonts" }}
{{-   end }}
["{{ $fontDir }}/MesloLGS NF Regular.ttf"]
    type = "file"
    url = "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS NF Regular.ttf"
    refreshPeriod = "168h"
["{{ $fontDir }}/MesloLGS NF Bold.ttf"]
    type = "file"
    url = "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS NF Bold.ttf"
    refreshPeriod = "168h"
["{{ $fontDir }}/MesloLGS NF Italic.ttf"]
    type = "file"
    url = "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS NF Italic.ttf"
    refreshPeriod = "168h"
["{{ $fontDir }}/MesloLGS NF Bold Italic.ttf"]
    type = "file"
    url = "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS NF Bold Italic.ttf"
    refreshPeriod = "168h"
{{- end }}
[".oh-my-bash"]
    type = "archive"
    url = "https://github.com/ohmybash/oh-my-bash/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".oh-my-zsh/custom/themes/powerlevel10k"]
    type = "archive"
    url = "https://github.com/romkatv/powerlevel10k/archive/v1.15.0.tar.gz"
    exact = true
    stripComponents = 1
{{- if (not (eq (env "REMOTE_CONTAINERS") "true")) }}
[".local/tfenv"]
    type = "archive"
    url = "https://github.com/tfutils/tfenv/archive/refs/tags/v3.0.0.tar.gz"
    exact = true
    stripComponents = 1
{{ $kubectlVersion := "1.25.7" }}
[".local/bin/kubectl"]
    type = "file"
    url = "https://dl.k8s.io/release/v{{ $kubectlVersion }}/bin/linux/amd64/kubectl"
    executable = true
    refreshPeriod = "168h"
{{ $helmVersion := "3.12.0" }}
[".local/bin/helm"]
    type = "file"
    url = "https://get.helm.sh/helm-v{{ $helmVersion }}-{{ .chezmoi.os }}-{{ .chezmoi.arch }}.tar.gz"
    executable = true
    refreshPeriod = "168h"
    [".local/bin/helm".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "{{ .chezmoi.os}}-{{ .chezmoi.arch }}/helm"]
{{ $istioVersion := "1.18.0" -}}
[".local/bin/istioctl"]
    type = "file"
    url = "https://github.com/istio/istio/releases/download/{{ $istioVersion }}/istioctl-{{ $istioVersion }}-{{ .chezmoi.os }}-{{ .chezmoi.arch }}.tar.gz"
    executable = true
    refreshPeriod = "168h"
    [".local/bin/istioctl".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "istioctl"]
{{ $awsIamAuthVersion := "0.5.9" }}
[".local/bin/aws-iam-authenticator"]
    type = "file"
    url = "https://github.com/kubernetes-sigs/aws-iam-authenticator/releases/download/v{{ $awsIamAuthVersion }}/aws-iam-authenticator_{{ $awsIamAuthVersion }}_linux_amd64"
    executable = true
    refreshPeriod = "168h"
{{ $clusterctlVersion := "1.4.3" }}
[".local/bin/clusterctl"]
    type = "file"
    url = "https://github.com/kubernetes-sigs/cluster-api/releases/download/v{{ $clusterctlVersion }}/clusterctl-linux-amd64"
    executable = true
    refreshPeriod = "168h"
{{ $kubectxVersion := "0.9.4" }}
[".local/bin/kubectx"]
    type = "file"
    url = "https://github.com/ahmetb/kubectx/releases/download/v{{ $kubectxVersion }}/kubectx_v{{ $kubectxVersion }}_linux_x86_64.tar.gz"
    executable = true
    refreshPeriod = "168h"
    [".local/bin/kubectx".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "kubectx"]
[".local/bin/kubens"]
    type = "file"
    url = "https://github.com/ahmetb/kubectx/releases/download/v{{ $kubectxVersion }}/kubens_v{{ $kubectxVersion }}_linux_x86_64.tar.gz"
    executable = true
    refreshPeriod = "168h"
    [".local/bin/kubens".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "kubens"]
{{ $fluxVersion := "2.1.2" }}
[".local/bin/flux"]
    type = "file"
    url = "https://github.com/fluxcd/flux2/releases/download/v{{ $fluxVersion }}/flux_{{ $fluxVersion }}_{{ .chezmoi.os }}_{{ .chezmoi.arch }}.tar.gz"
    executable = true
    refreshPeriod = "168h"
    [".local/bin/flux".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "flux"]
{{ $minikubeVersion := "1.31.2" }}
[".local/bin/minikube"]
    type = "file"
    url = "https://storage.googleapis.com/minikube/releases/v{{ $minikubeVersion }}/minikube-linux-amd64"
    executable = true
    refreshPeriod = "168h"
{{ $tfSwitchVersion := "0.13.1308" }}
[".local/bin/tfswitch"]
    type = "file"
    url = "https://github.com/warrensbox/terraform-switcher/releases/download/{{ $tfSwitchVersion }}/terraform-switcher_{{ $tfSwitchVersion }}_{{ .chezmoi.os }}_{{ .chezmoi.arch }}.tar.gz"
    executable = true
    refreshPeriod = "168h"
    [".local/bin/tfswitch".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "tfswitch"]
{{ $terraformDocsVersion := "v0.16.0" }}
[".local/bin/terraform-docs"]
    type = "file"
    url = "https://github.com/terraform-docs/terraform-docs/releases/download/v0.16.0/terraform-docs-{{ $terraformDocsVersion }}-{{ .chezmoi.os }}-{{ .chezmoi.arch }}.tar.gz"
    executable = true
    refreshPeriod = "168h"
    [".local/bin/terraform-docs".filter]
        command = "tar"
        args = ["--extract", "--file", "/dev/stdin", "--gzip", "--to-stdout", "terraform-docs"]
{{ $tflintVersion := "v0.48.0" }}
[".local/bin/tflint"]
    type = "archive-file"
    url = "https://github.com/terraform-linters/tflint/releases/download/{{ $tflintVersion }}/tflint_{{ .chezmoi.os }}_{{ .chezmoi.arch }}.zip"
    executable = true
    path = "tflint"
{{ $tfsecVersion := "v1.28.4" }}
[".local/bin/tfsec"]
    type = "file"
    url = "https://github.com/aquasecurity/tfsec/releases/download/{{ $tfsecVersion }}/tfsec-checkgen-{{ .chezmoi.os }}-{{ .chezmoi.arch }}"
    executable = true
{{- end }}
{{ $talosctlVersion := "1.5.5" }}
[".local/bin/talosctl"]
    type = "file"
    url = "https://github.com/siderolabs/talos/releases/download/v{{ $talosctlVersion }}/talosctl-linux-amd64"
    executable = true
{{ $skaffoldVersion := "2.9.0" }}
[".local/bin/skaffold"]
    type = "file"
    url = "https://storage.googleapis.com/skaffold/releases/v{{ $skaffoldVersion }}/skaffold-linux-amd64"
    executable = true
